### PR TITLE
fix: pass -latest to vswhere when a version is not specified

### PR DESCRIPTION
**Pull request by aminya**
Partially fixe_s #3

### CODE REVIEW

**Comment by MarkSchofield** [comment]
I've sent #5 that broadens the default version range to accommodate version 16.0 and higher, which means that VS2022 versions will be picked up. Removing `-latest` seems like the wrong thing to do. Thoughts?

**Comment by aminya** [comment]
If you notice, this does not remove `-latest` altogether. I just moved it under the version variable.

**Comment by MarkSchofield** [comment]
> If you notice, this does not remove -latest altogether. I just moved it under the version variable.

If '-latest' is only specified when a version is specified, and the version is off by default, then the default behavior is to return any non-"legacy" (which - I think - means VS2017 or higher) version in an unspecified order&dagger;. That sounds non-deterministic and confusing. '-latest' should *always* be specified, regardless of whether a version was provided. And the version range can be used to scope the range of '-latest'.

&dagger; I couldn't immediately find documentation on the order that installations are returned from vswhere. But even relying on that seems unnecessary when the toolchain only wants one version, and picking the latest of the matched versions seems ideal. Which is exactly what the '-latest' switch gets us.

> I prefer that vswhere gives up on the old versions, instead of the defaults overriding a strict version range.

Do you mean that you want to opportunistically consider pre-16.0 versions? That's fine, and opting-in to that by specifying "CMAKE_VS_VERSION_RANGE" would allow that. But by having the defaults accommodate a broad range of versions puts the burden on the project to perform due diligence verification of those versions, which just seems out-of-scope to me. The default version range spanning the most recent two versions of Visual Studio seems reasonable. If there are problems with older versions, then I'm happy for issues to be filed and discussed, but defaulting to more recent versions scopes expectations appropriately.

**Comment by aminya** [comment]
Technically, the difference between my PR and yours is mostly about the default version range, which you have chosen to be >=16. I think both solve the issue just in different ways.

**Pull request closed without merging**
